### ISSUE TITLE
Implications of 'choose "no" when it asks if you want to encrypt the wallet'

### ISSUE THREAD

**Issue by lestephane** [a5an0/ThunderCloud#9]
Why 'no'? Will it not be less insecure? The node is a hot wallet...

**Comment by a5an0** [comment]
(assuming you install `bos`, or I get around to fixing it in the setup script), there is a cronjob that will auto-unlock the wallet and systemd is making sure that `lnd` gets restarted if it dies. This is all so that if the node/lnd crashes, it comes back up on its own without you having to go and manually restart it. That won't work if the wallet is encrypted, unless you also keep the passphrase on disk next to it. Encrypting the wallet helps in the event that someone runs off with the disk, so having the key on disk doesn't help with anything.  An easy upgrade to the CDK stack would be to flip on ebs volume encryption. That way you're covered if someone snapshots the disk to another account or something. 

Encrypting the wallet doesn't help at all in the event that someone pwns your node: it's a hot wallet that LND has to have access to. Until we having the signing code in a secure enclave something, it all comes down to normal system hardening. 

 I suppose you could rig up something to keep the wallet encrypted with a key protected by KMS or something, but I haven't.

**Comment by lestephane** [comment]
I guess my question is thereby answered. LND can't really run securely AND reliably for the moment, because running reliably requires obtaining the wallet encryption key, and there is no provision for doing that securely. Someone would have to write an additional Go plugin to use the AWS KMS or Secret Manager SDK. I did not look into LND, but I guess it supports plugins.

>  An easy upgrade to the CDK stack would be to flip on ebs volume encryption. That way you're covered if someone snapshots the disk to another account or something.

I don't think encrypting the volume is any help if the node is compromised, since the entire (now compromised) EC2 instance then has the permission to read the volume's encrypted content anyway.

**Comment by a5an0** [comment]
yep. you got it.
